#!/bin/sh -h 
PYTHONHOME=/apps/synopsys/vcs-mx/N-2017.12/etc/search/pyh
export PYTHONHOME
PYTHONPATH=/apps/synopsys/vcs-mx/N-2017.12/linux64/lib/pylib27
export PYTHONPATH
LD_LIBRARY_PATH=/apps/synopsys/vcs-mx/N-2017.12/linux64/lib:/apps/synopsys/vcs-mx/N-2017.12/linux64/lib/pylib27
export LD_LIBRARY_PATH
/apps/synopsys/vcs-mx/N-2017.12/linux64/bin/vcsfind_create_index.exe  -z  "/home/thuan/Assignment2_s3574935/asic/vcs/simv.daidir/debug_dump/fsearch/./idents_tapi.xml.gz" "/home/thuan/Assignment2_s3574935/asic/vcs/simv.daidir/debug_dump/fsearch/./idents_HClM5y.xml.gz" -o "/home/thuan/Assignment2_s3574935/asic/vcs/simv.daidir/debug_dump/fsearch/fsearch.db_tmp"
\mv "/home/thuan/Assignment2_s3574935/asic/vcs/simv.daidir/debug_dump/fsearch/fsearch.db_tmp" "/home/thuan/Assignment2_s3574935/asic/vcs/simv.daidir/debug_dump/fsearch/fsearch.db"
